- name: Packer GitHub Actions
  uses: hashicorp/packer-github-actions@v0.2.0

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: aws-ubuntu-apache.pkr.hcl

      # build artifact
      - name: Build Golden Image
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: aws-ubuntu-apache.pkr.hcl
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts