---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          # if you have/need it
          aws-region: eu-central-1

      # Initialize Packer templates
      - name: Initialize Packer Template
        uses: lomar92/github-actions-packer@v0.3
        with:
          command: init
          target: images/aws-ubuntu-apache.pkr.hcl
                    
      # validate templates
      - name: Validate Template
        uses: lomar92/github-actions-packer@v0.3
        with:
          command: validate
          arguments: -syntax-only
          target: images/aws-ubuntu-apache.pkr.hcl

      # build artifact
      - name: Build Artifact
        uses: lomar92/github-actions-packer@v0.3
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: images/aws-ubuntu-apache.pkr.hcl
        env:
          PACKER_LOG: 1
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}

      # additional steps to process artifacts
